### PR TITLE
Added Polymer guide

### PR DESCRIPTION
**Pull request by klan**
#4

### CODE REVIEW

**Comment by klan** [comment]
I'm currently in the process of creating an iconset for Polymer with all the icons included. I will update my PR with instructions when ready :)

**Comment by klan** [comment]
Instructions for adding a iconset and generating a custom iconset has been added

**Comment by Templarian** [comment]
Just let me know when you want it merged. Don't worry too much about small pull requests/edit after this is merged. It's expected.

**Comment by klan** [comment]
I'm done for now, you can merge :)

**Pull request merged**
