### PR TITLE
Add documentation about PHP integration

### PR DESCRIPTION
**Pull request by quentin-st**
This PR adds some documentation about PHP / Twig integration

### CODE REVIEW

**Comment by Templarian** [comment]
@chteuchteu Just use the GitHub editor (please don't commit more than once ever minute or it could break the build, 🤣 )

You're added as a contributor on this repo now.

**Comment by quentin-st** [comment]
@Templarian Awesome, thank you! :-)

Since I'm not that comfortable with Angular, I like to test on my local env to ensure I don't break anything :-)

**Comment by Templarian** [comment]
I meant for the markdown text changes. There appears to be a smaller error at the bottom breaking.

http://dev.materialdesignicons.com/getting-started/php 😄

**Comment by quentin-st** [comment]
@Templarian Whoops indeed, my bad. My IDE kept adding them, I switched to VS Code since it's the one you seem to use
Can I edit the faulty file?

**Comment by Templarian** [comment]
Sure, I just fixed the sidebar and added the PHP icon.

**Comment by quentin-st** [comment]
Nice, thanks! GitHub's editor was not able to remove the empty line, and produced an empty commit (https://github.com/Templarian/MaterialDesign-Site/commit/caca4321f349f022708661fe3c5c7485b23a9de2) so I made the change locally and pushed it (https://github.com/Templarian/MaterialDesign-Site/commit/3ed5b624dd63d090b64a8e1f0836d7c2e4454ec2)

Isn't there any way to prevent the whole thing from breaking if there is a final empty line?

**Comment by Templarian** [comment]
Yea, probably a bug in my code I'll have to fix. Can you mean an issue describing the bug. Docs are a large part of the new site, so need to make sure that feature works good.

**Comment by quentin-st** [comment]
Here it is! https://github.com/Templarian/MaterialDesign-Site/issues/51

**Pull request merged**
