### PR TITLE
Add reference to Vue setup

### PR DESCRIPTION
**Pull request by robcresswell**

### CODE REVIEW

**Comment by robcresswell** [comment]
Just porting this reference over from the old website. The README for that lib is pretty detailed; did you want me to copy over some of the getting started steps? This feels like duplication to me, but I can understand wanting some more content in this site.

**Comment by Templarian** [comment]
Oops, didn't mean to close this

**Comment by Templarian** [comment]
Probably advise to moving to [MaterialDesign-JS](https://github.com/Templarian/MaterialDesign-JS) after Sunday's release. This should cut down in the overhead of working with `@mdi/svg` directly.

**Comment by robcresswell** [comment]
@Templarian I wasn't aware of that repo! That will save a few lines of code. Thanks!

**Pull request merged**
