### PR TITLE
Update getting-started-windows.md

### PR DESCRIPTION
**Pull request by alansingfield**
Added a link to VectorIcon UserControl for WPF.

### CODE REVIEW

**Review by Templarian — APPROVED** [review]

**Comment by Templarian** [comment]
Should be live on the site now. 😃

**Comment by MrGrigri** [comment]
The text is not a link

image

**Comment by Templarian** [comment]
Weird, must have turned off auto links. Looks like it will need to be updated. I'll just do it quick.

**Comment by alansingfield** [comment]
Thanks - link is working now.

**Pull request merged**
